full_name = "Islam Taha"
description = "Sr. Automation Software Test Engineer at CodeScalers who love coding & hacking. Hacking involves different ways of looking at problems that no one thought of it"
why_threefold = "With the age of private information leakage, I believe we need a next-generation solution to save our privacy and that is what exactly Threebot does."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
